[package]
name = "vestroll-vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }
vestroll-common = { path = "../common" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["alloc", "testutils"] }